

PROJECT_SOURCEFILES += config.c
PROJECTDIRS += ../modules/config
	
ifeq ($(TARGET),native)
PROJECT_SOURCEFILES += config-native.c 
endif


ifeq ($(TARGET),cc26x0-cc13x0)
PROJECT_SOURCEFILES += config-cc26xx.c
endif

ifeq ($(TARGET),simplelink)
PROJECT_SOURCEFILES += config-cc26xx.c
endif


bar:
	@echo $(TARGET)
	@echo $(PROJECT_SOURCEFILES)
