

PROJECT_SOURCEFILES += config.c
PROJECTDIRS += ../modules/config
	
ifeq ($(TARGET),native)
PROJECT_SOURCEFILES += config-native.c 
endif


ifeq ($(TARGET),srf06-cc26xx)
PROJECT_SOURCEFILES += config-cc26xx.c
endif


bar:
	@echo $(TARGET)
	@echo $(PROJECT_SOURCEFILES)
